### ISSUE TITLE
Call reservations with chosen address space instead of /24

### ISSUE THREAD

**Issue by omerzubair** [XtratusCloud/terraform-provider-azureipam#11]
First of all thanks for providing this . it works fine and best part is when I want to decommission a vnet I can simply remove config and it will call the api and decommission and free up the slots from ipam solution. :) 

**Address Space 
============**

Currently you have config which allows to send size by using "size" i.e if I send 24 then I get carved out reservation of /24 from the block mentioned in api. 

However, for my existing solution to work I need to send complete existing address space "10.71.26.0/23" to ipam solution and get the tag returned so that it is being tracked. I can do that manually by going to ipam solution interface, but it is against the automation have already have in AzDO pipelines. 

**Postman example:
============**

Luckily after talking with @DCMattyG, there is an api already in [ipam solution](https://github.com/Azure/ipam) which when called with complete address space will do that work. Please if you can help update your provider with the same capability as the api. that would be awesome .

![image](https://github.com/XtratusCloud/terraform-provider-azureipam/assets/7728453/d92d9ffd-ed9d-4407-a7c4-f241468f15be)

**Comment by omerzubair** [comment]
Hi Team, 
I am actively working on this. can this be acknowledged please? 
Happy to test this for feedback immediately.
cheers

**Comment by XtratusCloud** [comment]
H @omerzubair,
We have pending to analyze the last changes added to the azureipam solution to transfer them to the provider, and probably this is one of them, we will take it into consideration.

This is an opensource project, and the changes and improvements are made in our free time, you must understand that it will not be finished in a few days.  

Regards,

**Comment by omerzubair** [comment]
thanks for the reply. Eagerly awaiting :)

**Comment by XtratusCloud** [comment]
Implemented in [v2.0.0](https://github.com/XtratusCloud/terraform-provider-azureipam/releases/tag/v2.0.0)
