### ISSUE TITLE
Create spaces/blocks based on reservations and re-use the created space/blocks for new reservations

### ISSUE THREAD

**Issue by MMollyy** [XtratusCloud/terraform-provider-azureipam#12]
**Is your feature request related to a problem? Please describe.**
Would it be possible to add a resource which creates a space and block, based off of a reservation that was previously made.

For instance, if I have 192.168.0.0/16 in a space/block manually configured:
Create reservations for /18 (these become vnet in azure)

Followed with a resource that writes that reservation as a space and block into ipam?
So that next a reservation can be made on the created space/block. (for subnets inside the vnet)

**Describe the solution you'd like**
a new resource which creates the space/block, with attributes for space and block.

**Describe alternatives you've considered**
I've considered splitting up my terraform repository into multiple. Having the pipeline extract the CIDR from the initial reservation and using either python requests lib or powershell to create the space/block. Then have the pipeline send those values over to the next repository to trigger it with those inputs.

**Additional context**
I am currently using multiple modules to create the base networking functionality to be able to deploy across different regions, and to expand that base functionality easily by using a count across the resources. The subnets requiring reservations in the vnets, and the vnets requiring reservations in the cidr pools available to me.

In this feature request it is not possible to create blocks in the space, because the subnets would overlap with the range of the vnet. But I could imagine wanting to add just blocks into a space after a reservation was made as well.
For example:
Region = space
VNET = block

each single VNET = space
subnets = blocks

**Comment by XtratusCloud** [comment]
Hi @MMollyy ,
After reading your request I think we would meet your requirements adding to the provider several resources to maintain and query both spaces and blocks. 
This functionality is possible, and reasonably uncomplicated, as the IPAM API allows these actions.

We will take your implementation into consideration, but we are a small team and it may take some time.

Thank you for your collaboration

**Comment by fnietoga** [comment]
This functionality is implemented in commit 73783d1, and will be included in next v2.0.0 of provider.

**Comment by XtratusCloud** [comment]
Implemented in [v2.0.0](https://github.com/XtratusCloud/terraform-provider-azureipam/releases/tag/v2.0.0)
