### ISSUE TITLE
azureipam_reservation example usage is wrong

### ISSUE THREAD

**Issue by SaumyaBhushan** [XtratusCloud/terraform-provider-azureipam#5]
**Describe the bug**
azureipam_reservation example usage azurerm_virtual_network resource block does not contain right resource_group_name

**Expected behavior**
resource_group_name = azurerm_resource_group.example.name
**Screenshots**

![Screenshot from 2023-07-11 13-25-14](https://github.com/XtratusCloud/terraform-provider-azureipam/assets/76432998/c3ad68cf-abbe-42be-a91b-056d7bdcc879)

**Desktop (please complete the following information):**
 - Browser and version [e.g. chrome, safari, edge]
 - Terraform version
 - Other relevant providers

**Additional context**
https://registry.terraform.io/providers/XtratusCloud/azureipam/latest/docs/resources/reservation

**Comment by XtratusCloud** [comment]
The new release v1.0.1 already includes the requested changes.
Thanks for your contribution
