### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by jwieren** [XtratusCloud/terraform-provider-azureipam#6]
**Is your feature request related to a problem? Please describe.**
I would like to use your terraform provider, but there currently is no license file attached to this repository.

**Describe the solution you'd like**
I would like an open source license to be added to this repository. Preferably an Apache 2.0 or BSD 3-Clause.

**Comment by XtratusCloud** [comment]
thanks for your suggestion
I will check the most common opensource licenses and will add one shortly.

**Comment by XtratusCloud** [comment]
The new release v1.0.1 already includes the requested changes.
We have included an Apache v2 license.

Thanks for your contribution
